# Generated by Django 3.1.5 on 2021-02-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEn',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_parent_id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area_code', models.CharField(blank=True, max_length=20, null=True)),
                ('area_name', models.CharField(blank=True, max_length=50, null=True)),
                ('area_level', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'area_en',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('indicator_id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('indicator_order', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'indicator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorClassification',
            fields=[
                ('classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('classification_parent_id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('classification_name', models.CharField(blank=True, max_length=90, null=True)),
                ('classification_order', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'indicator_classification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorUnitSubgroup',
            fields=[
                ('iusnid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'indicator_unit_subgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('subgroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('subgroup_name', models.CharField(blank=True, max_length=20, null=True)),
                ('subgroup_order', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'subgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tab1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_id', models.IntegerField(blank=True, null=True)),
                ('indicator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('classification_id', models.IntegerField(blank=True, null=True)),
                ('indicator_order', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=40, null=True)),
                ('subgroup_id', models.IntegerField(blank=True, null=True)),
                ('subgroup_name', models.CharField(blank=True, max_length=20, null=True)),
                ('subgroup_order', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area_id', models.IntegerField(blank=True, null=True)),
                ('area_parent_id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area_code', models.CharField(blank=True, max_length=20, null=True)),
                ('area_name', models.CharField(blank=True, max_length=50, null=True)),
                ('area_level', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('timeperiod_id', models.IntegerField(blank=True, null=True)),
                ('timeperiod', models.CharField(blank=True, max_length=90, null=True)),
                ('data_value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'tab1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tab2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_id', models.IntegerField(blank=True, null=True)),
                ('indicator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('classification_id', models.IntegerField(blank=True, null=True)),
                ('indicator_order', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=40, null=True)),
                ('subgroup_id', models.IntegerField(blank=True, null=True)),
                ('subgroup_name', models.CharField(blank=True, max_length=20, null=True)),
                ('subgroup_order', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area_id', models.IntegerField(blank=True, null=True)),
                ('area_parent_id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area_code', models.CharField(blank=True, max_length=20, null=True)),
                ('area_name', models.CharField(blank=True, max_length=50, null=True)),
                ('area_level', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('timeperiod_id', models.IntegerField(blank=True, null=True)),
                ('timeperiod', models.CharField(blank=True, max_length=90, null=True)),
                ('data_value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'tab2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tab3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_id', models.IntegerField(blank=True, null=True)),
                ('indicator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('classification_id', models.IntegerField(blank=True, null=True)),
                ('indicator_order', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=40, null=True)),
                ('subgroup_id', models.IntegerField(blank=True, null=True)),
                ('subgroup_name', models.CharField(blank=True, max_length=20, null=True)),
                ('subgroup_order', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area_id', models.IntegerField(blank=True, null=True)),
                ('area_parent_id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area_code', models.CharField(blank=True, max_length=20, null=True)),
                ('area_name', models.CharField(blank=True, max_length=50, null=True)),
                ('area_level', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('timeperiod_id', models.IntegerField(blank=True, null=True)),
                ('timeperiod', models.CharField(blank=True, max_length=90, null=True)),
                ('data_value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'tab3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tab4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_id', models.IntegerField(blank=True, null=True)),
                ('indicator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('classification_id', models.IntegerField(blank=True, null=True)),
                ('indicator_order', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=40, null=True)),
                ('subgroup_id', models.IntegerField(blank=True, null=True)),
                ('subgroup_name', models.CharField(blank=True, max_length=20, null=True)),
                ('subgroup_order', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area_id', models.IntegerField(blank=True, null=True)),
                ('area_parent_id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area_code', models.CharField(blank=True, max_length=20, null=True)),
                ('area_name', models.CharField(blank=True, max_length=50, null=True)),
                ('area_level', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('timeperiod_id', models.IntegerField(blank=True, null=True)),
                ('timeperiod', models.CharField(blank=True, max_length=90, null=True)),
                ('data_value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'tab4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_id_tab4', models.IntegerField(blank=True, null=True)),
                ('indicator_name_tab4', models.CharField(blank=True, max_length=255, null=True)),
                ('classification_id_tab4', models.IntegerField(blank=True, null=True)),
                ('indicator_order_tab4', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('unit_id_tab4', models.IntegerField(blank=True, null=True)),
                ('unit_name_tab4', models.CharField(blank=True, max_length=40, null=True)),
                ('subgroup_id_tab4', models.IntegerField(blank=True, null=True)),
                ('subgroup_name_tab4', models.CharField(blank=True, max_length=20, null=True)),
                ('subgroup_order_tab4', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area_id_tab4', models.IntegerField(blank=True, null=True)),
                ('area_parent_id_tab4', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area_code_tab4', models.CharField(blank=True, max_length=20, null=True)),
                ('area_name_tab4', models.CharField(blank=True, max_length=50, null=True)),
                ('area_level_tab4', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('timeperiod_id_tab4', models.IntegerField(blank=True, null=True)),
                ('timeperiod_tab4', models.CharField(blank=True, max_length=90, null=True)),
                ('data_value_tab4', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'tabs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timeperiod',
            fields=[
                ('timeperiod_id', models.AutoField(primary_key=True, serialize=False)),
                ('timeperiod', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'db_table': 'timeperiod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'ut_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtDataCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.IntegerField(blank=True, null=True)),
                ('iusnid', models.IntegerField(blank=True, null=True)),
                ('timeperiod_id', models.IntegerField(blank=True, null=True)),
                ('area_id', models.IntegerField(blank=True, null=True)),
                ('indicator_id', models.IntegerField(blank=True, null=True)),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('subgroup_id', models.IntegerField(blank=True, null=True)),
                ('data_value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'ut_data_copy',
                'managed': False,
            },
        ),
    ]
